import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';

import { cn } from '@/shared/lib/utils';
import { Footer } from '@/shared/ui/components/footer';
import { Header } from '@/shared/ui/components/header';

import './globals.css';

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(urbanist.variable, 'antialiased')}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
