import {
  Header,
  HighlightedText,
  PolicyContentLayout,
  PolicyLayout,
  PolicySection,
} from '@/features/policies/components';

import { List } from '@/shared/ui/components/list';
import { Text } from '@/shared/ui/kit/text';
import { Title } from '@/shared/ui/kit/title';

export default function PrivacyPolicy() {
  return (
    <PolicyLayout>
      <Header title="Privacy Policy" updatedOn="05/05/2025" />
      <PolicyContentLayout>
        <PolicySection>
          <Title size="md" as="h3">
            Contact Information
          </Title>
          <Text>
            Optisence (“we,” “our,” or “us”) is committed to protecting your
            privacy. This Privacy Policy explains how Optisence collects, uses,
            and discloses your personal information. By accessing or using our
            Service, you signify that you have read, understood, and agree to
            our collection, storage, use, and disclosure of your personal
            information as described in this Privacy Policy.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Key Definitions and Important Terms
          </Title>
          <List
            values={[
              'Cookie: A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you, such as your language preference or login information.',
              'Company: When this Policy mentions “Company,” “we,” “us,” or “our,” it refers to Krouder Pty Ltd (registered at 134 Bree Street, Cape Town City Centre, Cape Town, Western Cape, 8000 with registered number 334070), which is responsible for your information under this Privacy Policy.',
              'Country: Where Optisence or the owners/founders of Optisence are based, in this case, in South Africa.',
              'Customer: Refers to the company, organisation, or person that signs up to use the Optisence Service to manage the relationships with your consumers or service users.',
              'Device: Any internet-connected device such as a phone, tablet, computer, or other device that can be used to visit Optisence and use the services.',
              'IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often identify the location from which a device connects to the Internet.',
              'Personnel: Refers to those employed by Optisence or are under contract to perform a service on behalf of one of the parties.',
              'Personal Data: Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.',
              'Service: Refers to the service provided by Optisence as described in the relative terms (if available) and on this platform.',
              'Third-Party Service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.',
              'Website: Krouder Pty Ltd’s site, which can be accessed via this URL: www.optisence.com.',
              'You: A person or entity registered with Optisence to use the Services.',
            ]}
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Types of Information We Collect
          </Title>
          <Text>
            We collect information from you when you visit our website,
            register, place an order, subscribe to our newsletter, respond to a
            survey, or fill out a form:
          </Text>
          <List
            values={[
              'Name / Username',
              'Phone Numbers',
              'Email Addresses',
              'Mailing Addresses',
              'Billing Addresses',
              'Age',
              'Password',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            How We Utilize Your Data
          </Title>
          <Text>
            Any of the information we collect from you may be used in one of the
            following ways:
          </Text>
          <List
            values={[
              'To personalise your experience (your information helps us to better respond to your individual needs);',
              'To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you);',
              'To improve customer service (your information helps us to respond to your customer service requests and support needs more effectively);',
              'To process transactions;',
              'To administer a contest, promotion, survey, or other site feature;',
              'To send periodic emails.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Information Shared With Third Parties
          </Title>
          <Text>
            Optisence will collect End User Data necessary to provide the
            Optisence services to our customers. End users may voluntarily
            provide us with the information they have made available on social
            media websites. If you provide us with such information, we may
            collect publicly available information from the social media
            websites you have indicated. You can control how much of your
            information social media websites make public by visiting these
            websites and changing your privacy settings.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Data Collection by External Sources
          </Title>
          <Text>
            We receive some information from third parties when you contact us.
            For example, when you submit your email address to us to show
            interest in becoming an Optisence customer, we receive information
            from a third party that provides automated fraud detection services
            to Optisence. We also occasionally collect information that is made
            publicly available on social media websites. You can control how
            much of your information social media websites make public by
            visiting these websites and changing your privacy settings.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            How We Distribute Your Information
          </Title>
          <Text>
            We may share the information that we collect, both personal and
            non-personal, with third parties such as advertisers, contest
            sponsors, promotional and marketing partners, and others who provide
            our content or whose products or services we think may interest you.
            We may also share it with our current and future affiliated
            companies and business partners. If we are involved in a merger,
            asset sale, or other business reorganisation, we may share or
            transfer your personal and non-personal information to our
            successors-in-interest.
          </Text>
          <Text>
            We may engage trusted third-party service providers to perform
            functions and provide services to us, such as hosting and
            maintaining our servers and the website, database storage and
            management, email management, storage marketing, credit card
            processing, customer service, and fulfilling orders for products and
            services you may purchase through the website. We will likely share
            your personal and possibly some non-personal information with these
            third parties to enable them to perform these services for us and
            you.
          </Text>
          <Text>
            We may share portions of our log file data, including IP addresses,
            for analytics purposes with third parties such as web analytics
            partners, application developers, and ad networks. If your IP
            address is shared, it may be used to estimate general location and
            other technographics such as connection speed, whether you have
            visited the website in a shared location, and the type of device
            used to visit it. They may aggregate information about our
            advertising and what you see on the website and provide auditing,
            research, and reporting for us and our advertisers.
          </Text>
          <Text>
            We may also disclose personal and non-personal information about you
            to government or law enforcement officials or private parties as we,
            in our sole discretion, believe necessary or appropriate to respond
            to claims, legal processes (including subpoenas) to protect our
            rights and interests, or those of a third party, the safety of the
            public or any person, to prevent or stop any illegal, unethical, or
            legally actionable activity, or to otherwise comply with applicable
            court orders, laws, rules and regulations.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Use of Your Email Address
          </Title>
          <Text>
            By submitting your email address on this website, you agree to
            receive emails from us. You can cancel participation in these email
            lists by clicking the opt-out link or other unsubscribe options in
            the email. We only email people authorised to contact them directly
            or through a third party. We do not send unsolicited commercial
            emails because we hate spam as much as you do.
          </Text>
          <Text>
            By submitting your email address, you also agree to allow us to use
            your email address for customer audience targeting on sites like
            Facebook, where we display custom advertising to specific people who
            have opted-in to receive communications from us. Email addresses
            submitted only through the order processing page will be used to
            send you information and updates about your order. If, however, you
            have provided the same email to us through another method, we may
            use it for any of the purposes stated in this Policy. Note: If at
            any time you would like to unsubscribe from receiving future emails,
            we include detailed unsubscribe instructions at the bottom of each
            email.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Protection of Your Information
          </Title>
          <Text>
            We implement a variety of security measures to maintain the safety
            of your personal information when you place an order or enter,
            submit, or access your personal information. We offer the use of a
            secure server. All supplied sensitive/credit information is
            transmitted via Secure Socket Layer (SSL) technology and then
            encrypted into our Payment gateway providers’ database only to be
            accessible by those authorised with special access rights to such
            systems and are required to keep the information confidential.
          </Text>
          <Text>
            After a transaction, your private information (credit cards, social
            security numbers, financials, etc.) is never kept on file. We
            cannot, however, ensure or warrant the absolute security of any
            information you transmit to Optisence or guarantee that your
            information on the Service may not be accessed, disclosed, altered,
            or destroyed by a breach of any of our physical, technical, or
            managerial safeguards.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Data Security Measures
          </Title>
          <Text>
            We take precautions to protect the security of your information. We
            have physical, electronic, and managerial procedures to help
            safeguard, prevent unauthorised access, maintain data security, and
            correctly use your information. However, neither people nor security
            systems are foolproof, including encryption systems.
          </Text>
          <Text>
            In addition, people can commit intentional crimes, make mistakes, or
            fail to follow policies. Therefore, while we use reasonable efforts
            to protect your personal information, we cannot guarantee its
            security. If applicable law imposes any non-disclaimable duty to
            protect your personal information, you agree that intentional
            misconduct will be the standard to measure our compliance with that
            duty.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Your Rights to Access and Modify Your Data
          </Title>
          <Text>
            Your rights to request updates or corrections to the information
            Optisence collects depend on your relationship with Optisence.
            Personnel may update or correct their information as detailed in our
            internal company employment policies.
          </Text>
          <Text>
            Customers have the right to request the restriction of specific uses
            and disclosures of personally identifiable information. You can
            contact us to:
          </Text>
          <List
            values={[
              'Update or correct your personally identifiable information.',
              'Change your preferences concerning communications and other information you receive from us.',
              'Cancelling your account will delete the personally identifiable information maintained about you on our systems (subject to the following paragraph).',
            ]}
            noHighlight
          />
          <Text>
            Such updates, corrections, changes, and deletions will not affect
            other information that we maintain or have provided to third parties
            by this Privacy Policy before such updates, corrections, changes, or
            deletions. To protect your privacy and security, we may take
            reasonable steps (such as requesting a unique password) to verify
            your identity before granting you profile access or making
            corrections. You are responsible for maintaining the secrecy of your
            unique password and account information.
          </Text>
          <Text>
            You should be aware that it is not technologically possible to
            remove every record of the information you have provided us from our
            system. The need to back up our systems to protect information from
            accidental loss means that a copy of your information may exist in a
            non-erasable form that will be difficult or impossible for us to
            locate. Promptly after receiving your request, all personal
            information stored in databases we actively use, and other readily
            searchable media will be updated, corrected, changed, or deleted, as
            appropriate, as soon as and to the extent reasonably and technically
            practicable.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Disclosing Your Information to Others
          </Title>
          <Text>
            We may disclose information (including personal information) about
            you to our Corporate Affiliates. For purposes of this Privacy
            Policy, “Corporate Affiliate” means any person or entity that
            directly or indirectly controls is controlled by, or is under common
            control with Optisence, whether by ownership or otherwise. Those
            Corporate Affiliates will treat any information relating to you that
            we provide to our Corporate Affiliates following the terms of this
            Privacy Policy.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Applicable Legal Regulations
          </Title>
          <Text>
            The laws of <HighlightedText>South Africa</HighlightedText> govern
            this Privacy Policy without regard to its conflict of laws
            provision. You consent to the exclusive jurisdiction of the courts
            in connection with any action or dispute arising between the parties
            under or in connection with this Privacy Policy. The laws of{' '}
            <HighlightedText>South Africa</HighlightedText>, excluding its
            conflicts of law rules, shall govern this Agreement and your use of
            the website. Your website use may also be subject to local, state,
            national, or international laws.
          </Text>
          <Text>
            Using Optisence or contacting us directly signifies your acceptance
            of this Privacy Policy. If you disagree with this Privacy Policy,
            you should not engage with our website or use our services.
            Continued use of the website, direct engagement with us, or
            following the posting of changes to this Privacy Policy that do not
            significantly affect the use or disclosure of your personal
            information will mean that you accept those changes.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Your Agreement to Data Usage
          </Title>
          <Text>
            We’ve updated our Privacy Policy to provide complete transparency
            into what is set when you visit our site and its use. By using our
            website, registering an account, or purchasing, you now consent to
            our Privacy Policy and agree to its terms.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Protection of Children’s Privacy
          </Title>
          <Text>
            We do not address anyone under 18 and do not knowingly collect
            personally identifiable information from anyone under 18. If you are
            a parent or guardian and know that your child has provided us with
            Personal Data, please get in touch with us. Suppose we become aware
            that we have collected Personal Data from anyone under the age of 18
            without verification of parental consent. In that case, we will
            remove that information from our servers.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Modifications to Our Privacy Policy
          </Title>
          <Text>
            We may change our Services and policies, and we may need to make
            changes to this Privacy Policy so that they accurately reflect our
            Services and policies. Unless otherwise required by law, we will
            notify you (for example, through our Service) before we make changes
            to this Privacy Policy and allow you to review them before they go
            into effect. Then, if you continue to use the Service, you will be
            bound by the updated Privacy Policy. You can delete your account if
            you disagree with this or any revised Privacy Policy.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Cookies and Tracking Technologies
          </Title>
          <Text color="primary" size="lg">
            Use of Google Maps API
          </Text>
          <List
            values={[
              'Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data synching with location, plan routes, or create a mashup, just to name a few.',
              'Google Maps API may collect information from You and Your Device for security purposes.',
              'Google Maps API collects information that its Privacy Policy holds.',
            ]}
            noHighlight
          />
          <Text color="primary" size="lg">
            Cookie Information
          </Text>
          <List
            values={[
              'We may collect and use your information if you are from the European Economic Area (EEA). This section of our Privacy Policy explains exactly how and why this data is collected and how we protect it from replication or misuse.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Summary of GDPR Compliance
          </Title>
          <Text>
            GDPR is an EU-wide privacy and data protection law regulating how
            companies protect EU residents’ data companies and enhances the
            control EU residents have over their data. The GDPR is relevant to
            any globally operating company, not just EU-based businesses and EU
            residents. Our customers’ data is essential irrespective of
            location, so we have implemented GDPR controls as our baseline
            standard for all our operations worldwide.
          </Text>
          <Text>
            The Data Protection Principles include requirements such as:
          </Text>
          <List
            values={[
              'Personal data collected must be processed fairly, legally, and transparently and only used in a way that a person would reasonably expect.',
              'Personal data should only be collected to fulfil a specific purpose and should only be used for that purpose. Organisations must specify why they need personal data when they collect it.',
              'Personal data should be held no longer than necessary to fulfil its purpose.',
              'People covered by the GDPR have the right to access their data. They can also request a copy of their data and that their data be updated, deleted, restricted, or moved to another organisation.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Your Rights: Access, Portability & Deletion
          </Title>
          <Text>
            We are committed to helping our customers meet the GDPR’s data
            subject rights requirements. Optisence processes or stores all
            personal data in fully vetted, DPA-compliant vendors. We store all
            conversations and personal data for up to 6 years unless your
            account is deleted. In this case, we dispose of all data following
            our Terms of Service and Privacy Policy, but we will not hold it for
            longer than 60 days.
          </Text>
          <Text>
            We know that if you are working with EU customers, you need to be
            able to give them access to, update, retrieve, and remove personal
            data. We got you! We’ve been set up as self-service and have always
            given you access to your and your customers’ data. Our customer
            support team is here to answer any questions about working with the
            API.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            How to Contact Us
          </Title>
          <Text>For any questions you have, please get in touch with us:</Text>
          <List
            values={[
              {
                text: 'Email: info@optisence.com',
                href: 'mailto:info@optisence.com',
              },
              'Phone number: NUMBER',
              { text: 'Visit our Contact page: Contact Us', href: '/contact' },
            ]}
          />
        </PolicySection>
      </PolicyContentLayout>
    </PolicyLayout>
  );
}
