import {
  Header,
  HighlightedText,
  PolicyContentLayout,
  PolicyLayout,
  PolicySection,
} from '@/features/policies/components';

import { List } from '@/shared/ui/components/list';
import { Url } from '@/shared/ui/components/url';
import { Text } from '@/shared/ui/kit/text';
import { Title } from '@/shared/ui/kit/title';

export default function TermsAndConditions() {
  return (
    <PolicyLayout>
      <Header title="Terms and Conditions" updatedOn="05/05/2025" />
      <PolicyContentLayout>
        <PolicySection>
          <Title size="md" as="h3">
            Contact Information
          </Title>
          <Text>
            By accessing and placing an order with Optisence, you confirm that
            you are in Agreement with and bound by the Terms and Conditions
            outlined below. These Terms apply to the entire website and any
            email or other communication between you and{' '}
            <HighlightedText>Krouder Pty Ltd</HighlightedText>, operated under
            Optisence and registered at{' '}
            <HighlightedText>
              134 Bree Street, Cape Town City Centre, Cape Town, Western Cape,
              8000
            </HighlightedText>
            .
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            License to Use
          </Title>
          <Text>
            These Terms and Conditions are a contract between you and{' '}
            <HighlightedText>Krouder Pty Ltd</HighlightedText> (referred to in
            these Terms and Conditions as “Optisence,” “us,” “we,” or “our”),
            the provider of the Optisence website (
            <Url value="www.optisence.com" />) and the services accessible from
            the Optisence website (which are collectively referred to in these
            Terms and Conditions as the “Optisence Service”). You agree to be
            bound by these Terms and Conditions. Please do not use the Optisence
            Service if you disagree with these Terms and Conditions. In these
            Terms and Conditions, “you” refers to you as an individual and the
            entity you represent. If you violate any of these Terms and
            Conditions, we reserve the right to cancel your account or block
            access to your account without notice.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Key Terms and Definitions
          </Title>
          <Text>For these Terms and Conditions:</Text>
          <List
            values={[
              'Cookie: Small data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you, such as your language preference or login information.',
              'Company: When this Policy mentions “Company,” “we,” “us,” or “our,” it refers to Krouder Pty Ltd (registered at 134 Bree Street, Cape Town City Centre, Cape Town, Western Cape, 8000 with registered number 334070),  is responsible for your information under these Terms and Conditions.',
              'Country: Where Optisence or the owners/founders of Optisence are based, in this case, in South Africa.',
              'Device: Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Optisence and use the services.',
              'Service: Refers to the Service provided by Optisence as described in the relative terms (if available) and on this platform.',
              'Third-Party Service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.',
              'Website: Krouder Pty Ltd’s site, accessed via this URL www.optisence.com.',
              'You: A person or entity registered with Optisence to use the Services.',
            ]}
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Age Verification
          </Title>
          <Text>
            To ensure that our services are used by individuals who meet the
            legal requirements for entering into a binding contract, Optisence
            requires that all users be{' '}
            <HighlightedText>18 or older</HighlightedText>, or the minimum age
            required for entering into contractual agreements in their
            respective jurisdiction. If you are under{' '}
            <HighlightedText>18</HighlightedText> or do not meet the minimum
            legal age for contracts in your jurisdiction, you are prohibited
            from accessing certain services or features on the Optisence
            website.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            User Restrictions
          </Title>
          <Text>You agree not to, and you will not permit others to:</Text>
          <List
            values={[
              'Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of Optisence or its affiliates, partners, suppliers, or the licensors of the website.',
              'Licence, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or commercially exploit the website or make the platform available to any third party.',
              'Modify, do derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the website.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Submissions and Feedback
          </Title>
          <Text>
            Any feedback, comments, ideas, improvements, or suggestions
            (collectively, “Suggestions”) you provide to Optisence concerning
            the website shall remain the sole and exclusive property of
            Optisence. Optisence shall be free to use, copy, modify, publish, or
            redistribute the Suggestions for any purpose and in any way without
            any credit or any compensation to you.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Your Consent to Our Terms
          </Title>
          <Text>
            We’ve updated our Terms and Conditions to provide complete
            transparency into what is being set when you visit our site and how
            it’s used. By using our website, registering an account, or
            purchasing, you hereby consent to our Terms and Conditions.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Changes to Our Terms and Conditions
          </Title>
          <Text>
            You acknowledge and agree that Optisence may stop (permanently or
            temporarily) providing the Service (or any features within the
            Service) to you or users generally at Optisence’s sole discretion
            without prior notice. You may stop using the Service at any time.
            You do not need to inform Optisence when you stop using the Service.
            You acknowledge and agree that if Optisence disables access to your
            account, you may be prevented from accessing the Service, your
            account details, or any files or other materials contained in your
            account.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Updates to Our Terms
          </Title>
          <Text>
            We may change our Services and policies and need to make changes to
            these Terms so that they accurately reflect our Services and
            policies. Unless otherwise required by law, we will notify you (for
            example, through our Service) before we make changes to these Terms
            and allow you to review them before they go into effect. Then, if
            you continue to use the Service, you will be bound by the updated
            Terms. You can delete your account if you do not want to agree to
            these or any updated Terms.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Website Modifications
          </Title>
          <Text>
            Optisence reserves the right to modify, suspend, or discontinue,
            temporarily or permanently, the website or any service to which it
            connects, with or without notice and without liability to you.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Updates to Our Website
          </Title>
          <Text>
            Optisence may occasionally provide enhancements or improvements to
            the features/ functionality of the website, which may include
            patches, bug fixes, updates, upgrades, and other modifications
            (“Updates”). Updates may modify or delete certain website features
            and/or functionalities. You agree that Optisence has no obligation
            to (i) provide any Updates or (ii) continue to provide or enable any
            particular features and/or functionalities of the website to you.
            You further agree that all Updates will be (i) deemed an integral
            part of the website and (ii) subject to the Terms and Conditions of
            this Agreement.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Third-Party Services
          </Title>
          <Text>
            We may display, include, or make available third-party content
            (including data, information, applications, and other product
            services) or provide links to third-party websites or services
            (“Third-Party Services”). You acknowledge and agree that Optisence
            shall not be responsible for any Third-Party Services, including
            their accuracy, completeness, timeliness, validity, copyright
            compliance, legality, decency, quality, or any other aspect thereof.
            Optisence does not assume and shall not have any liability or
            responsibility to you or any other person or entity for any
            Third-Party Services. Third-party services and links thereto are
            provided solely for your convenience, and you access and use them
            entirely at your own risk and subject to such third parties’ Terms
            and Conditions.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Term and Termination
          </Title>
          <Text>
            This Agreement shall remain in effect until you or Optisence
            terminates it. Optisence may, in its sole discretion, suspend or
            terminate this Agreement with or without prior notice at any time
            and for any or no reason. This Agreement will terminate immediately,
            without prior notice from Optisence, if you fail to comply with any
            provision of this Agreement. You may also terminate this Agreement
            by deleting the website and all copies from your computer.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Links to Other Websites
          </Title>
          <Text>
            These Terms and Conditions apply only to the Services. The Services
            may contain links to other websites not operated or controlled by
            Optisence. We are not responsible for the content, accuracy, or
            opinions expressed on such websites, and such websites are not
            investigated, monitored, or checked for accuracy or completeness by
            us. Please remember that when you use a link from the Services to
            another website, our Terms and Conditions are no longer in effect.
            Your browsing and interaction on any other website, including those
            with a link on our platform, is subject to that website’s rules and
            policies. Third parties may use cookies or other methods to collect
            information about you.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Cookie Policy
          </Title>
          <Text>
            Optisence uses “Cookies” to identify the areas of our website that
            you have visited. A cookie is a small piece of data stored on your
            computer or mobile device by your web browser. We use cookies to
            enhance the performance and functionality of our website, but they
            are non-essential to their use. However, without these cookies,
            certain functionality, like videos, may become unavailable, or you
            would be required to enter your login details every time you visit
            the website, as we could not remember that you had logged in
            previously. Most web browsers can be set to disable the use of
            Cookies. However, if you disable Cookies, you may not be able to
            access functionality on our website correctly or at all. We never
            place Personally Identifiable Information in Cookies. Please explore
            our <Url value="/cookie-policy" placeholder="Cookie Policy" /> for
            more information.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Copyright Notice
          </Title>
          <Text>
            If you are a copyright owner or such owner’s agent and believe any
            material on our website constitutes an infringement on your
            copyright, please get in touch with us setting forth the following
            information:
          </Text>
          <List
            values={[
              'A physical or electronic signature of the copyright owner or someone authorised to act on his behalf. ',
              'Identification of the material that is claimed to be infringing.',
              'Your contact information, including your address, telephone number, and email.',
              'A statement by you that you have a good faith belief that the copyright owners do not authorise the use of the material.',
              'A statement that the information in the notification is accurate and, under penalty of perjury, you are authorised to act on behalf of the owner.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            No Warranties
          </Title>
          <Text>
            The website is provided to you “AS IS” and “AS AVAILABLE” with all
            faults and defects without warranty of any kind. To the maximum
            extent permitted under applicable law, Optisence, on its behalf and
            on behalf of its affiliates and their respective licensors and
            service providers, expressly disclaims all warranties, whether
            express, implied, statutory, or otherwise, concerning the website,
            including all implied warranties of merchantability, fitness for a
            particular purpose, title and non-infringement, and warranties that
            may arise out of a course of dealing, course of performance, usage
            or trade practice.
          </Text>
          <Text>
            Without limitation to the foregoing, Optisence provides no warranty
            or undertaking. It makes no representation of any kind that the
            website will meet your requirements, achieve any intended results,
            be compatible or work with any other software, systems, or services,
            operate without interruption, meet any performance or reliability
            standards, or be error-free or that any errors or defects can or
            will be corrected. Without limiting the preceding, neither Optisence
            nor any Optisence provider makes any representation or warranty of
            any kind, express or implied:
          </Text>
          <List
            values={[
              'Regarding the operation or availability of the website or the information, content, materials, or products included thereon.',
              'That the website will be uninterrupted or error-free.',
              'Your contact information, including your address, telephone number, and email.',
              'The accuracy, reliability, or currency of any information or content provided through the website.',
              'The website, its servers, the content, or emails sent from or on behalf of Optisence are free of viruses, scripts, trojan horses, worms, malware, time bombs, or other harmful components. Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Liability Limitation
          </Title>
          <Text>
            Notwithstanding any damages you might incur, the entire liability of
            Optisence and any of its suppliers under any provision of this
            Agreement and your exclusive remedy for all of the previous shall be
            limited to the amount actually paid by you for the website. To the
            maximum extent permitted by applicable law, in no event shall
            Optisence or its suppliers be liable for any special, incidental,
            indirect, or consequential damages whatsoever (including, but not
            limited to, damages for loss of profits, for loss of data or other
            information, for business interruption, for personal injury, for
            loss of privacy arising out of or in any way related to the use of
            or inability to use the website, third-party software and/or
            third-party hardware used with the website, or otherwise in
            connection with any provision of this Agreement), even if Optisence
            or any supplier has been advised of the possibility of such damages
            and even if the remedy fails of its essential purpose. Some
            jurisdictions do not allow the exclusion or limitation of incidental
            or consequential damages, so the above limitation or exclusion may
            not apply to you.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Indemnification
          </Title>
          <Text>
            You agree to indemnify and hold Optisence and its parents,
            subsidiaries, affiliates, officers, employees, agents, partners, and
            licensors (if any) harmless from any claim or demand, including
            reasonable attorneys’ fees, due to or arising out of your:
          </Text>
          <List
            values={[
              'Use of the website',
              'Violation of this Agreement or any law or regulation.',
              'Violation of any right of a third party.',
            ]}
            noHighlight
          />
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Severability
          </Title>
          <Text>
            With the{' '}
            <Url value="/privacy-policy" placeholder="Privacy Policy" /> and any
            other legal notices published by Optisence on the Services, this
            Agreement shall constitute the entire Agreement between you and
            Optisence concerning the Services. Suppose any provision of this
            Agreement is deemed invalid by a court of competent jurisdiction. In
            that case, the invalidity of such provision shall not affect the
            validity of the remaining provisions of this Agreement, which shall
            remain in full force and effect. No term of this Agreement shall be
            deemed a further or continuing waiver of such or any other term.
            Optisence’s failure to assert any right or provision under this
            Agreement shall not constitute a waiver of such right or provision.
            You and Optisence agree that any cause of action arising from or
            related to the services must commence within one (1) year after the
            cause of action accrues. Otherwise, such cause of action is
            permanently barred.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Waiver of Rights
          </Title>
          <Text>
            Except as provided herein, the failure to exercise a right or to
            require the performance of an obligation under this Agreement shall
            not affect a party’s ability to exercise such right or require such
            performance at any time thereafter, nor shall the waiver of a breach
            constitute waiver of any subsequent breach.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Entire Agreement
          </Title>
          <Text>
            The Agreement constitutes the entire Agreement between you and
            Optisence regarding your website use. It supersedes all prior and
            contemporaneous written or oral agreements.
            <br /> You may be subject to additional Terms and Conditions when
            you use or purchase other Optisence services, which Optisence will
            provide at the time of such use or purchase.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Amendments to This Agreement
          </Title>
          <Text>
            Optisence reserves the right, at its sole discretion, to modify or
            replace this Agreement at any time. If a revision is material, we
            will provide at least 30 days’ notice before any new Terms take
            effect. What constitutes a material change will be determined at our
            sole discretion.
            <br />
            By continuing to access or use our website after any revisions
            become effective, you agree to be bound by the revised Terms. If you
            disagree with the new Terms, you can no longer use Optisence.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Intellectual Property Rights
          </Title>
          <Text>
            The website and its entire contents, features, and functionality
            (including but not limited to all information, software, text,
            displays, images, video and audio, and the design, selection, and
            arrangement thereof) are owned by Optisence, its licensors, or other
            providers of such material.{' '}
            <HighlightedText>South Africa</HighlightedText> and international
            copyright, trademark, patent, trade secret, and other intellectual
            property or proprietary rights laws protect them. The material may
            not be copied, modified, reproduced, downloaded, or distributed in
            any way, in whole or in part, without the express prior written
            permission of Optisence unless and except as expressly provided in
            these Terms and Conditions. Any unauthorised use of the material is
            prohibited.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Agreement to Arbitrate
          </Title>
          <Text>
            This section applies to any dispute, except it doesn’t include a
            dispute relating to claims for injunctive or equitable relief
            regarding the enforcement or validity of your or Optisence’s
            intellectual property rights. The term “dispute” means any dispute,
            action, or other controversies between you and Optisence concerning
            the Services or this Agreement, whether in contract, warranty, tort,
            statute, regulation, ordinance, or any other legal or equitable
            basis. “Dispute” will be given the broadest possible meaning
            allowable under law.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Binding Arbitration
          </Title>
          <Text>
            If a dispute arises and the parties fail to resolve it through
            informal negotiation, all further efforts to resolve the dispute
            shall be conducted exclusively by binding arbitration following the
            <HighlightedText>
              rules of the International Chamber of Commerce (ICC)
            </HighlightedText>{' '}
            (or other chosen institution). By agreeing to these Terms, you waive
            any rights to litigate disputes before a judge or jury, including as
            a class member. The dispute will be settled through arbitration in
            <HighlightedText>Cape Town, South Africa</HighlightedText>, or
            another location mutually agreed upon by the parties.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Notice of Dispute
          </Title>
          <Text>
            In the event of a dispute, you or Optisence must give the other a
            Notice of Dispute, a written statement that sets forth the name,
            address, and contact information of the party giving it, the facts
            giving rise to the dispute, and the relief requested. You must send
            any Notice of Dispute via email to{' '}
            <Url
              value="mailto:info@optisence.com"
              placeholder="info@optisence.com"
            />
            . Optisence will mail any Notice of Dispute to you if we have it or
            otherwise to your email address. You and Optisence will attempt to
            resolve any dispute through informal negotiation within sixty (60)
            days from the date the Notice of Dispute is sent. After sixty (60)
            days, you or Optisence may commence arbitration.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Governing Law
          </Title>
          <Text>
            These Terms and Conditions are governed by and construed by the laws
            of <HighlightedText>South Africa</HighlightedText>, without regard
            to its conflict of law principles. By accessing or using the
            Optisence website and services, you agree that any legal action or
            proceeding under these Terms shall be brought exclusively in the
            <HighlightedText>Cape Town, South Africa</HighlightedText> courts.
            You further consent to the personal jurisdiction of these courts,
            waiving any objection based on venue or inconvenience.
          </Text>
          <Text>
            If there is a legal dispute or disagreement between you and
            Optisence arising from our services, it will be resolved under{' '}
            <HighlightedText>South African</HighlightedText> law. You agree to
            submit to the exclusive jurisdiction and venue of the courts of{' '}
            <HighlightedText>Cape Town</HighlightedText>, which shall be the
            only forum for any claim or legal action.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Submissions and Privacy
          </Title>
          <Text>
            If you submit or post any ideas, creative suggestions, designs,
            photographs, information, advertisements, data, or proposals,
            including ideas for new or improved products, services, features,
            technologies, or promotions, you expressly agree that such
            submissions will automatically be treated as non-confidential and
            non-proprietary and will become the sole property of Optisence
            without any compensation or credit to you whatsoever. Optisence and
            its affiliates shall have no obligations concerning such submissions
            or posts. They may use the ideas contained in such submissions or
            posts for any purposes in any medium in perpetuity, including, but
            not limited to, developing manufacturing and marketing products and
            services using such ideas.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Promotions
          </Title>
          <Text>
            Optisence may sometimes include contests, promotions, sweepstakes,
            or other activities (“Promotions”) that require you to submit
            material or information concerning yourself. Please note that all
            promotions may be governed by separate rules containing certain
            eligibility requirements, such as age and geographic location
            restrictions. You are responsible for reading all Promotions rules
            to determine whether or not you are eligible to participate. If you
            enter any Promotion, you agree to abide by and comply with all
            Promotions Rules.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Typographical Errors
          </Title>
          <Text>
            Suppose a product and/or Service is listed at an incorrect price or
            with incorrect information due to a typographical error. In that
            case, we shall have the right to refuse or cancel any orders for the
            product and/or Service listed at the incorrect price. We shall have
            the right to refuse or cancel any such order whether or not the
            order has been confirmed and your credit card charged. If your
            credit card has already been charged for the purchase and your order
            is canceled, we shall immediately issue a credit to your credit card
            account or other payment accounts in the amount of the charge.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Disclaimer
          </Title>
          <Text>
            Optisence is not responsible for content, code, or other
            imprecision. Optisence does not provide warranties or guarantees. In
            no event shall Optisence be liable for any special, direct,
            indirect, consequential, or incidental damages or any damages
            whatsoever, whether in an action of contract, negligence, or other
            torts, arising out of or in connection with the use of the Service
            or the contents of the Service. Optisence reserves the right to make
            additions, deletions, or modifications to the contents of the
            Service at any time without prior notice.
          </Text>
          <Text>
            The Optisence Service and its contents are provided “as are” and “as
            available” without any warranty or representations, express or
            implied. Optisence is a distributor and not a publisher of the
            content supplied by third parties; as such, Optisence exercises no
            editorial control over such content and makes no warranty or
            representation as to the accuracy, reliability, or currency of any
            information, content, Service or merchandise provided through or
            accessible via the Optisence Service.
          </Text>
        </PolicySection>
        <PolicySection>
          <Title size="md" as="h3">
            Contact Information
          </Title>
          <Text>
            If you have any questions or concerns regarding these Terms and
            Conditions, please do not hesitate to contact us at:
          </Text>
          <List
            values={[
              {
                text: 'Email: info@optisence.com',
                href: 'mailto:info@optisence.com',
              },
              'Phone number: NUMBER',
              { text: 'Visit our Contact page: Contact Us', href: '/contact' },
            ]}
          />
        </PolicySection>
      </PolicyContentLayout>
    </PolicyLayout>
  );
}
